version: '3.8'

services:
  molly-socket:
    image: ghcr.io/mollyim/mollysocket:latest
    container_name: molly-socket
    restart: unless-stopped
    network_mode: host
    command: server
    env_file:
      - .env
    environment:
      - MOLLY_PORT=8080
      - MOLLY_HOST=0.0.0.0
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"